// <auto-generated />
using System;
using ChatData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatData.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20210225220657_Unread_Messages")]
    partial class Unread_Messages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatData.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            MessageType = 0,
                            RoomId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Text = "Message1",
                            Time = new DateTime(2021, 2, 25, 22, 6, 56, 629, DateTimeKind.Utc).AddTicks(8864),
                            UserId = new Guid("5e78f76e-3bb5-41b8-8df9-1b951c6570f7")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            MessageType = 0,
                            RoomId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Text = "Message2",
                            Time = new DateTime(2021, 2, 25, 22, 6, 56, 630, DateTimeKind.Utc).AddTicks(3394),
                            UserId = new Guid("5e78f76e-3bb5-41b8-8df9-1b951c6570f7")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            MessageType = 0,
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Text = "Message3",
                            Time = new DateTime(2021, 2, 25, 22, 6, 56, 630, DateTimeKind.Utc).AddTicks(3582),
                            UserId = new Guid("5e78f76e-3bb5-41b8-8df9-1b951c6570f7")
                        });
                });

            modelBuilder.Entity("ChatData.Models.Participants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastMessageDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LastMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            LastMessageDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMessageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoomId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("5e78f76e-3bb5-41b8-8df9-1b951c6570f7")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            LastMessageDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMessageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoomId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("5e78f76e-3bb5-41b8-8df9-1b951c6570f7")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            LastMessageDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMessageId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("5e78f76e-3bb5-41b8-8df9-1b951c6570f7")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            LastMessageDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMessageId = new Guid("11111111-1111-1111-1111-111111111111"),
                            RoomId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("e8854ae6-b79d-4d22-a680-e7be40c2c694")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            LastMessageDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMessageId = new Guid("22222222-2222-2222-2222-222222222222"),
                            RoomId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UserId = new Guid("e8854ae6-b79d-4d22-a680-e7be40c2c694")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            LastMessageDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastMessageId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoomId = new Guid("33333333-3333-3333-3333-333333333333"),
                            UserId = new Guid("e8854ae6-b79d-4d22-a680-e7be40c2c694")
                        });
                });

            modelBuilder.Entity("ChatData.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Room 1",
                            Type = "Type1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Room 2",
                            Type = "Type2"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Room 3",
                            Type = "Type3"
                        });
                });

            modelBuilder.Entity("ChatData.Models.Message", b =>
                {
                    b.HasOne("ChatData.Models.Room", "Room")
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ChatData.Models.Participants", b =>
                {
                    b.HasOne("ChatData.Models.Room", "Room")
                        .WithMany("Participants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("ChatData.Models.Room", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
